
language: swift
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3
script:
  - xcodebuild clean build -project Tatsi.xcodeproj -scheme Tatsi -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1'
# Testing has been removed for now because the tests require photos access, which can not be automaticlly granted in unit tests.
# - xcodebuild clean build test -project Tatsi.xcodeproj -scheme Tatsi -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1'
